name: Invitation
description: inviteme to NGcodex
title: "invite me "
labels: ["invitation"]
assignees:
  - ngdream
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: name
    attributes:
      label: name
      description: add your name
      placeholder: nguewo fossong christian
    validations:
      required: true
  - type: checkboxes
    id: languages
    attributes:
      label: your programming languages
      description: which is your programming languages ??
      options:
        - label: c
          required: true
        - label: c++
          required: true         
        - label: python
          required: true
